AWSTemplateFormatVersion: '2010-09-09'
Description: "Media Insights Engine - Workflow to run Instant Translate"

Parameters:

  WorkflowCustomResourceArn:
    Type: String
    Description: "ARN of the Media Insights custom resource that handles creating operations, stages and workflows"
  OperatorLibraryStack:
    Description: "Name of the operator library stack"
    Type: String
  ShortUUID:
    Type: String
    Description: "A short UUID that is going to be appended to resource names"

Resources:
  # Stages

  MediaconvertStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "ITMediaconvertStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:Mediaconvert"
  TranscribeStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "ITTranscribeStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:Transcribe"
  TranslateStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "ITTranslateStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:Translate"
  PollyStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "ITPollyStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:Polly"

  # Workflow

  InstantTranslateWorkflow:
    DependsOn:
      - MediaconvertStage
      - TranscribeStage
      - TranslateStage
      - PollyStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: !Sub "InstantTranslateWorkflow-${ShortUUID}"
      StartAt: !GetAtt MediaconvertStage.Name
      Stages: !Sub
        - |-
          {
            "${MediaconvertStage}":{
              "Next": "${TranscribeStage}"
              },
            "${TranscribeStage}":{
              "Next": "${TranslateStage}"
              },
            "${TranslateStage}":{
              "Next": "${PollyStage}"
              },
            "${PollyStage}":{
              "End": true
              }
          }
        - {
            MediaconvertStage: !GetAtt MediaconvertStage.Name,
            TranscribeStage: !GetAtt TranscribeStage.Name,
            TranslateStage: !GetAtt TranslateStage.Name,
            PollyStage: !GetAtt PollyStage.Name
          }
