AWSTemplateFormatVersion: '2010-09-09'
Description: "Media Insights Engine - Workflow to run Transcriber app"

Parameters:

  WorkflowCustomResourceArn:
    Type: String
    Description: "ARN of the Media Insights custom resource that handles creating operations, stages and workflows"
  OperatorLibraryStack:
    Description: "Name of the operator library stack"
    Type: String
  ShortUUID:
    Type: String
    Description: "A short UUID that is going to be appended to resource names"

Resources:
  # Stages

  MediaconvertStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "MediaconvertStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:Mediaconvert"
  TranscribeStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "TranscribeStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:Transcribe"
  WebCaptionsStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "WebCaptionsStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:WebCaptions"
  CreateTimeSeriesStage:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Stage"
      Name: !Sub "CreateTimeSeriesStage-${ShortUUID}"
      Operations:
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:WebToSRTCaptions"
        - Fn::ImportValue:
            Fn::Sub: "${OperatorLibraryStack}:WebToVTTCaptions"

  # Workflow

  TranscribeWorkflow:
    DependsOn:
      - MediaconvertStage
      - TranscribeStage
      - WebCaptionsStage
      - CreateTimeSeriesStage
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref WorkflowCustomResourceArn
      ResourceType: "Workflow"
      Name: !Sub "TranscribeWorkflow-${ShortUUID}"
      StartAt: !GetAtt MediaconvertStage.Name
      Stages: !Sub
        - |-
          {
            "${MediaconvertStage}":{
              "Next": "${TranscribeStage}"
              },
            "${TranscribeStage}":{
              "Next": "${WebCaptionsStage}"
              },
            "${WebCaptionsStage}":{
              "Next": "${CreateTimeSeriesStage}"
              },
            "${CreateTimeSeriesStage}":{
              "End": true
              }
          }
        - {
          MediaconvertStage: !GetAtt MediaconvertStage.Name,
          TranscribeStage: !GetAtt TranscribeStage.Name,
          WebCaptionsStage: !GetAtt WebCaptionsStage.Name,
          CreateTimeSeriesStage: !GetAtt CreateTimeSeriesStage.Name
        }
